Areas/admin/Models/SanPham.cs
namespace Nhom1_VanPhongPham.Areas.admin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SanPham")]
    public partial class SanPham
    {
        [Key]
        [DisplayName("Mã sản phẩm")]
        public int MaSanPham { get; set; }

        [Required]
        [StringLength(100)]
        [DisplayName("Tên sản phẩm")]
        public string TenSanPham { get; set; }

        [DisplayName("Tổng số lượng")]
        public int TongSoLuong { get; set; }

        [StringLength(50)]
        [DisplayName("Xuất xứ")]
        public string XuatXu { get; set; }

        [StringLength(50)]
        [DisplayName("Quy cách")]
        public string QuyCach { get; set; }

        [StringLength(50)]
        [DisplayName("Đơn vị tính")]
        public string DonViTinh { get; set; }

        [DisplayName("Mã danh mục")]
        public int MaDanhMuc { get; set; }

        [Column(TypeName = "ntext")]
        [DisplayName("Ảnh sản phẩm")]
        public string AnhSanPham { get; set; }
    }
}

Models/SanPham.cs
namespace Nhom1_VanPhongPham.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SanPham")]
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            SanPhamMauSacs = new HashSet<SanPhamMauSac>();
        }

        [Key]
        public int MaSanPham { get; set; }

        [Required]
        [StringLength(100)]
        public string TenSanPham { get; set; }

        public int TongSoLuong { get; set; }

        [StringLength(50)]
        public string XuatXu { get; set; }

        [StringLength(50)]
        public string QuyCach { get; set; }

        [StringLength(50)]
        public string DonViTinh { get; set; }

        public int MaDanhMuc { get; set; }

        [Column(TypeName = "ntext")]
        public string AnhSanPham { get; set; }

        [Column(TypeName = "numeric")]
        [DisplayFormat(DataFormatString = "{0:#,###}")]
        public decimal? GiaSanPham { get; set; }

        [StringLength(1000)]
        public string MoTa { get; set; }

        public virtual DanhMuc DanhMuc { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPhamMauSac> SanPhamMauSacs { get; set; }
    }
}

Areas/admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Nhom1_VanPhongPham.Areas.admin.Dto;
using Nhom1_VanPhongPham.Areas.admin.Models;
using PagedList;

namespace Nhom1_VanPhongPham.Areas.admin.Controllers
{
    public class SanPhamsController : Controller
    {
        private Model1 db = new Model1();

        // GET: admin/SanPhams
        public ActionResult Index(int page = 1, string search = "")
        {
            ViewBag.search = search;
            var sanPhams = db.SanPhams.Select(item => item)
                .OrderBy(item => item.MaSanPham)
                .Where(item => item.TenSanPham.Contains(search));
            return View(sanPhams.ToPagedList(page, 10));
        }

        // GET: admin/SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }

            List<SanPhamMauSac> spMsList = db.SanPhamMauSacs.Select(item => item)
                .Where(item => item.MaSanPham == id)
                .ToList();
            ViewBag.sanPhamMauSacList = spMsList;
            return View(sanPham);
        }

        // GET: admin/SanPhams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: admin/SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSanPham,TenSanPham,TongSoLuong,XuatXu,QuyCach,DonViTinh,MaDanhMuc,AnhSanPham")] SanPham sanPham)
        {
            var colors = Request.Params["colors"];
            var quantities = Request.Params["quantities"];
            var file = Request.Files["imgProd"];
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string fileName = file.FileName.Trim();
                    file.SaveAs(Server.MapPath("~/wwwroot/img/") + fileName);
                    sanPham.AnhSanPham = fileName;
                    if(quantities != null && quantities.Length > 0)
                    {
                        sanPham.TongSoLuong = quantities.Split(',').Sum(i => int.Parse(i));
                    }
                }

                db.SanPhams.Add(sanPham);
                db.SaveChanges();

                //save color
                if (colors != null && colors.Length > 0)
                {
                    string[] arrQuantity = quantities.Split(',');
                    string[] arrColor = colors.Split(',');
                    for(int i = 0; i< arrColor.Length; i ++)
                    {
                        MauSac savedColor = this.saveColor(arrColor[i]);
                        this.saveProductColor(sanPham, savedColor, arrQuantity[i]);
                    }
                }

                return RedirectToAction("Index");
            }
            return View(sanPham);
        }

        // GET: admin/SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }

            List<SanPhamMauSac> spMsList = db.SanPhamMauSacs.Select(item => item)
                .Where(item => item.MaSanPham == id)
                .ToList();
            ViewBag.sanPhamMauSacList = new JavaScriptSerializer().Serialize(spMsList);

            return View(sanPham);
        }

        // POST: admin/SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSanPham,TenSanPham,TongSoLuong,XuatXu,QuyCach,DonViTinh,MaDanhMuc,AnhSanPham")] SanPham sanPham)
        {
            var colors = Request.Params["colors"];
            var quantities = Request.Params["quantities"];
            
            if(colors != null && quantities !=null)
            {
                string[] arrColor = colors.Split(',');
                string[] arrQuantity = quantities.Split(',');
                sanPham.TongSoLuong = arrQuantity.Sum(item => int.Parse(item));

                for(int i= 0; i< arrColor.Length;i ++)
                {
                    var colorCode = arrColor[i];
                    SanPhamMauSac spMs =  db.SanPhamMauSacs.Select(el => el)
                        .Where(el => el.MaMau.Equals(colorCode) && el.MaSanPham == sanPham.MaSanPham).First();
                    if(spMs != null)
                    {
                        spMs.SoLuongCon = int.Parse(arrQuantity[i]);
                        db.Entry(spMs).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }
            }
            
            var file = Request.Files["imgProd"];
            if (ModelState.IsValid)
            {
                if (file != null && file.ContentLength > 0)
                {
                    string fileName = file.FileName.Trim();
                    file.SaveAs(Server.MapPath("~/wwwroot/img/") + fileName);
                    sanPham.AnhSanPham = fileName;
                }

                db.Entry(sanPham).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sanPham);
        }

        // GET: admin/SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            List<SanPhamMauSac> listSpMs = db.SanPhamMauSacs.Select(spMs => spMs)
                .Where(spMs => spMs.MaSanPham == id)
                .ToList();
            listSpMs.ForEach(el => { 
                db.SanPhamMauSacs.Remove(el); 
                db.SaveChanges(); 
            });

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: admin/SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        protected MauSac saveColor(string colorCode)
        {
            MauSac mauSac = null;
            try
            {
                mauSac = db.MauSacs.Select(mau => mau)
                    .Where(mau => mau.MaMau.Equals(colorCode))
                    .First();
                return mauSac;
            }catch(Exception e)
            {
                mauSac = new MauSac();
                mauSac.MaMau = colorCode;
                mauSac =  db.MauSacs.Add(mauSac);
                db.SaveChanges();
                return mauSac;
            }
        }

        protected SanPhamMauSac saveProductColor(SanPham sp, MauSac mauSac, string quantity)
        {
            try
            {
                SanPhamMauSac spMs = new SanPhamMauSac();
                spMs.MaMau = mauSac.MaMau;
                spMs.MaSanPham = sp.MaSanPham;
                spMs.SoLuongCon = int.Parse(quantity);
                spMs = db.SanPhamMauSacs.Add(spMs);
                db.SaveChanges();
                return spMs;
            }catch(Exception e)
            {
                return null;
            }
        }
    }
}

Areas/admin/Views/SanPhams/Create.cshtml
@model Nhom1_VanPhongPham.Areas.admin.Models.SanPham

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm("Create","SanPhams" ,FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tạo mới sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TongSoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TongSoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TongSoLuong, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.XuatXu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.XuatXu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.XuatXu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuyCach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuyCach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuyCach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonViTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonViTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDanhMuc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDanhMuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imgProd" name="imgProd" hidden />
                <label for="imgProd" class="btn btn-sm btn-warning">Chọn ảnh</label>
            </div>
        </div>

        <div class="form-group" id="select-color">
            <label>Tùy chọn màu</label>
            <button class="btn btn-sm btn-primary" type="button" v-on:click="add()">Thêm</button>
            <div v-for="(item, index) in colors" :key="index">
                <input  type="color" name="colors" v-model="colors[index]" />
                <input type="number" name="quantities" min="0"/>
                <button type="button" class="btn btn-sm btn-danger" v-on:click="del(index)">delete</button>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div>
                    <input type="submit" value="Lưu" class="btn btn-sm btn-success" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Areas/admin/adminroot/js/vue.min.js"></script>
<script>
    new Vue({
        el: '#select-color',
        data() {
            return {
                colors: ["#ff4000"]
            }
        },
        methods: {
            add: function () {
                this.colors.push("#ff4000");
            },
            del: function (idx) {
                console.log("abc");
                this.colors = this.colors.filter((item, index, self) => index !== idx);
            }
        }
    })
</script>

Areas/admin/Views/SanPhams/Delete.cshtml
@model Nhom1_VanPhongPham.Areas.admin.Models.SanPham

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenSanPham)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TongSoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TongSoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.XuatXu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.XuatXu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuyCach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuyCach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonViTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonViTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaDanhMuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDanhMuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhSanPham)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhSanPham)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Areas/admin/Views/SanPhams/Details.cshtml
@model Nhom1_VanPhongPham.Areas.admin.Models.SanPham

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>Thông tin sản phẩm</h4>
    <hr />
    <table class="table">
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.TenSanPham)
            </td>

            <td>
                @Html.DisplayFor(model => model.TenSanPham)
            </td>
        </tr>

        <tr>
            <td>
                @Html.DisplayNameFor(model => model.TongSoLuong)
            </td>

            <td>
                @Html.DisplayFor(model => model.TongSoLuong)
            </td>
        </tr>

        <tr>
            <td>
                @Html.DisplayNameFor(model => model.XuatXu)
            </td>

            <td>
                @Html.DisplayFor(model => model.XuatXu)
            </td>
        </tr>

        <tr>
            <td>
                @Html.DisplayNameFor(model => model.QuyCach)
            </td>

            <td>
                @Html.DisplayFor(model => model.QuyCach)
            </td>
        </tr>

        <tr>
            <td>
                @Html.DisplayNameFor(model => model.DonViTinh)
            </td>

            <td>
                @Html.DisplayFor(model => model.DonViTinh)
            </td>
        </tr>

        <tr>
            <td>
                @Html.DisplayNameFor(model => model.MaDanhMuc)
            </td>

            <td>
                @Html.DisplayFor(model => model.MaDanhMuc)
            </td>
        </tr>

        <tr>
            <td>
                @Html.DisplayNameFor(model => model.AnhSanPham)
            </td>

            <td>
                @Html.DisplayFor(model => model.AnhSanPham)
            </td>
        </tr>

    </table>

    <div class="my-3">
        <label>Tùy chọn màu sắc</label>
        @foreach (var spms in ViewBag.sanPhamMauSacList)
        {
            <div>
                <input type="color" value="@spms.MaMau" readonly />
                <input type="number" value="@spms.SoLuongCon" readonly />
            </div>
        }
    </div>

</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaSanPham }, new { @class = "btn btn-sm btn-primary" })
    @Html.ActionLink("Quay về danh sách", "Index", null, new { @class = "btn btn-sm btn-warning" })
</p>

Areas/admin/Views/SanPhams/Edit.cshtml
@model Nhom1_VanPhongPham.Areas.admin.Models.SanPham

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cập nhật thông tin sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaSanPham)

        <div class="form-group">
            @Html.LabelFor(model => model.TenSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenSanPham, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenSanPham, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.TongSoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TongSoLuong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TongSoLuong, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.XuatXu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.XuatXu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.XuatXu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuyCach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuyCach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuyCach, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonViTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonViTinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonViTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaDanhMuc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaDanhMuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaDanhMuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhSanPham, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="imgProd" name="imgProd" hidden />
                <label for="imgProd" class="btn btn-sm btn-success">Chọn ảnh</label>
            </div>
        </div>

        <div class="form-group" id="vue-edit-color">
            <label>Tùy chọn màu sắc</label>
            <div v-for="item in spMsList" :key="item.MaMau">
                <input type="color" name="colors" v-model="item.MaMau" readonly />
                <br />
                <input type="number" min="0" name="quantities" v-model="item.SoLuongCon" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new {@class="btn btn-sm btn-warning" })
</div>

@{ 
    var spMsList = Html.Raw(Json.Encode(ViewBag.sanPhamMauSacList));
}


<script src="~/Areas/admin/adminroot/js/vue.min.js"></script>

<script>
    new Vue({
        el: '#vue-edit-color',
        data() {
            return {
                spMsList: JSON.parse(@spMsList)
            }
        }
    })
</script>

Areas/admin/Views/SanPhams/Index.cshtml
@model PagedList.IPagedList<Nhom1_VanPhongPham.Areas.admin.Models.SanPham>

@using PagedList.Mvc
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css"/>

<h2>Danh sách sản phẩm</h2>

<p>
    @Html.ActionLink("Thêm sản phẩm", "Create",null, new {@class="btn btn-sm btn-success" })
</p>
<form action="@Url.Action("Index")" method="post" class="form-inline">
    <input name="search" placeholder="Tìm kiếm" class="form-control form-control-sm" value="@ViewBag.search" />
    <button class="btn btn-sm btn-primary mx-3">Tìm kiếm</button>
</form>
<table class="table">
    <tr>
        <th>
            Tên sản phẩm
        </th>
        <th>
            Tổng số lượng
        </th>
        <th>
            Xuất xứ
        </th>
        <th>
            Đơn vị tính
        </th>
        <th>
            Mã danh mục
        </th>
        <th>
            Ảnh
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @item.TenSanPham
        </td>
        <td>
            @item.TongSoLuong
        </td>
        <td>
            @item.XuatXu
        </td>
        <td>
            @item.DonViTinh
        </td>
        <td>
            @item.MaDanhMuc
        </td>
        <td>
            <img src="@Url.Content("~/wwwroot/img/" + item.AnhSanPham)" width="100px" height="70px" />
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.MaSanPham }, new { @class="btn btn-sm btn-warning" } )
            @Html.ActionLink("Details", "Details", new { id=item.MaSanPham }, new { @class="btn btn-sm btn-success" } )
            @Html.ActionLink("Delete", "Delete", new { id=item.MaSanPham }, new { @class="btn btn-sm btn-danger" } )
        </td>
    </tr>
}

</table>

@Html.PagedListPager(Model, page => Url.Action("Index", new { page }))